//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amethyst_game_engine {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amethyst_game_engine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #version 330 core
        ///
        ///uniform vec3 color;
        ///
        ///out vec4 FragColor;
        ///
        ///void main()
        ///{
        ///    FragColor = vec4(color, 1.0);
        ///}
        ///.
        /// </summary>
        internal static string FragmentShader_0 {
            get {
                return ResourceManager.GetString("FragmentShader_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #version 330 core
        ///
        ///in vec4 color;
        ///
        ///out vec4 FragColor;
        ///
        ///void main()
        ///{
        ///    FragColor = color;
        ///}
        ///.
        /// </summary>
        internal static string FragmentShader_1 {
            get {
                return ResourceManager.GetString("FragmentShader_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #version 330 core
        ///
        ///layout (location = 0) in vec3 _position;
        ///
        ///uniform mat4 mesh;
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///
        ///void main()
        ///{
        ///    gl_Position = vec4(_position, 1.0) * mesh * model * view * projection;
        ///}
        ///.
        /// </summary>
        internal static string VertexShader_0 {
            get {
                return ResourceManager.GetString("VertexShader_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #version 330 core
        ///
        ///layout (location = 0) in vec3 _position;
        ///layout (location = 1) in vec4 _color;
        ///
        ///const vec4 defaultVertexColor = vec4(1.0);
        ///
        ///out vec4 color;
        ///
        ///uniform mat4 mesh;
        ///uniform mat4 model;
        ///uniform mat4 view;
        ///uniform mat4 projection;
        ///
        ///void main()
        ///{
        ///    color = _color;
        ///
        /////    if (length(color) == 0)
        /////        color = defaultVertexColor;
        ///
        ///    gl_Position = vec4(_position, 1.0) * mesh * model * view * projection;
        ///}
        ///.
        /// </summary>
        internal static string VertexShader_1 {
            get {
                return ResourceManager.GetString("VertexShader_1", resourceCulture);
            }
        }
    }
}
